# Generated by Django 2.2.28 on 2022-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('dt_txt', models.CharField(max_length=255)),
            ],
        ),
    ]
