# Generated by Django 2.2.28 on 2022-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_historyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='dt',
            field=models.IntegerField(default=1669755600),
            preserve_default=False,
        ),
    ]
