# Generated by Django 2.2.28 on 2022-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_historyitem_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='location',
            field=models.CharField(default='2346 Atterbury Road', max_length=255),
            preserve_default=False,
        ),
    ]
