# Generated by Django 2.2.28 on 2022-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_historyitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='temperature',
            field=models.CharField(default=295.23, max_length=255),
            preserve_default=False,
        ),
    ]
